### ISSUE TITLE
zwave hanging after reloading the jar

### ISSUE THREAD

**Issue by marcelrv** [cdjackson/HABmin#141]
Habmin is no longer functioning after zwave binding has been removed and loaded again due to AtmosphereFramework error:

steps: start OH, move the zwave binding jar out of addons folder. move it back to the addons folder. habmin is now no longer working

error in the log:

22:53:34.415 ERROR o.a.cpr.AtmosphereFramework[:682]- Failed to initialize Atmosphere Framework
javax.servlet.ServletException: Resource configuration class, org.openhab.io.rest.RESTApplication, is not a super class of class javax.ws.rs.core.Application
        at com.sun.jersey.spi.container.servlet.WebComponent.createResourceConfig(WebComponent.java:737)
        at com.sun.jersey.spi.container.servlet.WebComponent.createResourceConfig(WebComponent.java:674)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:203)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:374)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:557)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
22:53:41.517 ERROR o.a.cpr.AtmosphereFramework[:682]- Failed to initialize Atmosphere Framework
javax.servlet.ServletException: Resource configuration class, org.openhab.io.rest.RESTApplication, is not a super class of class javax.ws.rs.core.Application

**Comment by cdjackson** [comment]
Stale issue
