### ISSUE TITLE
Nodes dying restarting openhab does not init zwave device

### ISSUE THREAD

**Issue by grzech1983** [cdjackson/HABmin#207]
Hello,

from some days now I'm struggling with slowly (or not it depends how you look at it since all nodes can die during the night) node dying where I have situation that only zwave stick is green in habmin. I'm using most recent zwave binding from habmin repo. Interesting thing is that when I'm restarting openhab zwave device (Aeon Stick) is not being initialized:

```2015-01-14 07:48:54.322 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:18.606 DEBUG o.o.b.z.i.ZWaveActivator[:36]- Z-Wave binding has been started.
2015-01-14 07:52:18.952 DEBUG o.o.b.z.i.ZWaveActiveBinding[:183]- ConverterHandler not initialised. Polling disabled.
2015-01-14 07:52:18.959 INFO  o.o.b.z.i.ZWaveActiveBinding[:321]- Update config, port = /dev/zwave
2015-01-14 07:52:18.961 INFO  o.o.b.z.i.ZWaveActiveBinding[:326]- Update config, healtime = 2
2015-01-14 07:52:18.963 INFO  o.o.b.z.i.ZWaveActiveBinding[:371]- Update config, setSUC = true
2015-01-14 07:52:18.964 INFO  o.o.b.z.i.ZWaveActiveBinding[:380]- Update config, softReset = true
2015-01-14 07:52:18.966 INFO  o.o.b.z.i.ZWaveActiveBinding[:389]- Update config, masterController = true
2015-01-14 07:52:18.968 DEBUG o.o.b.z.i.ZWaveActiveBinding[:279]- Initialising zwave binding
2015-01-14 07:52:18.984 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:19.229 INFO  o.o.b.z.i.p.ZWaveController[:152]- Starting Z-Wave controller
2015-01-14 07:52:19.232 INFO  o.o.b.z.i.p.ZWaveController[:160]- Z-Wave timeout is set to 5000ms. Soft reset is true.
2015-01-14 07:52:19.234 INFO  o.o.b.z.i.p.ZWaveController[:389]- Connecting to serial port /dev/zwave
2015-01-14 07:52:19.505 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveReceiveThread[:1311]- Starting Z-Wave thread: Receive
2015-01-14 07:52:19.517 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1126]- Starting Z-Wave thread: Send
2015-01-14 07:52:19.526 INFO  o.o.b.z.i.p.ZWaveController[:409]- Serial port is initialized
2015-01-14 07:52:19.531 DEBUG o.o.b.z.i.p.ZWaveController[:1092]- Starting Z-Wave thread: Input
2015-01-14 07:52:19.543 DEBUG o.o.b.z.i.p.SerialMessage[:108]- NODE 255: Creating empty message of class = SerialApiSoftReset (0x08), type = Request (0x00)
2015-01-14 07:52:19.566 DEBUG o.o.b.z.i.p.SerialMessage[:232]- Assembled message buffer = 01 03 00 08 F4
2015-01-14 07:52:19.598 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveReceiveThread[:1376]- Receive Message = 01 0C 00 04 08 39 06 31 05 03 0A 00 03 FE
2015-01-14 07:52:19.643 DEBUG o.o.b.z.i.p.ZWaveController[:1098]- Receive queue TAKE: Length=0
2015-01-14 07:52:19.650 DEBUG o.o.b.z.i.p.ZWaveController[:177]- Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 08 39 06 31 05 03 0A 00 03
2015-01-14 07:52:19.652 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveReceiveThread[:1303]- Receive queue ADD: Length=0
2015-01-14 07:52:19.660 ERROR o.o.b.z.i.p.ZWaveController$ZWaveReceiveThread[:1391]- Message cancelled by controller (CAN), resending
2015-01-14 07:52:19.799 WARN  o.o.b.z.i.p.s.ApplicationCommandMessageClass[:34]- NODE 57: Not initialized yet, ignoring message.
2015-01-14 07:52:19.832 ERROR o.o.b.z.i.p.ZWaveController$ZWaveReceiveThread[:1409]- Got an exception during receiving. exiting thread.
java.lang.NullPointerException: null
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.enqueue(ZWaveController.java:501)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveReceiveThread.run(ZWaveController.java:1397)
2015-01-14 07:52:19.834 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveReceiveThread[:1411]- Stopped Z-Wave thread: Receive
2015-01-14 07:52:19.914 DEBUG o.o.b.z.i.p.SerialMessage[:108]- NODE 255: Creating empty message of class = GetVersion (0x15), type = Request (0x00)
2015-01-14 07:52:19.917 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1132]- Took message from queue for sending. Queue length = 0
2015-01-14 07:52:19.917 DEBUG o.o.b.z.i.p.ZWaveController[:518]- Enqueueing message. Queue length = 0
2015-01-14 07:52:19.927 DEBUG o.o.b.z.i.p.SerialMessage[:232]- Assembled message buffer = 01 03 00 15 E9
2015-01-14 07:52:19.931 DEBUG o.o.b.z.i.p.SerialMessage[:108]- NODE 255: Creating empty message of class = MemoryGetId (0x20), type = Request (0x00)
2015-01-14 07:52:19.934 DEBUG o.o.b.z.i.p.ZWaveController[:518]- Enqueueing message. Queue length = 1
2015-01-14 07:52:19.931 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1178]- NODE 255: Sending REQUEST Message = 01 03 00 15 E9
2015-01-14 07:52:19.943 DEBUG o.o.b.z.i.p.SerialMessage[:108]- NODE 255: Creating empty message of class = SerialApiGetCapabilities (0x07), type = Request (0x00)
2015-01-14 07:52:19.945 DEBUG o.o.b.z.i.p.ZWaveController[:518]- Enqueueing message. Queue length = 2
2015-01-14 07:52:19.953 DEBUG o.o.b.z.i.p.s.GetSucNodeIdMessageClass[:30]- Get SUC NodeID
2015-01-14 07:52:19.963 DEBUG o.o.b.z.i.p.SerialMessage[:108]- NODE 255: Creating empty message of class = GetSucNodeId (0x56), type = Request (0x00)
2015-01-14 07:52:19.965 DEBUG o.o.b.z.i.p.ZWaveController[:518]- Enqueueing message. Queue length = 3
2015-01-14 07:52:23.985 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:24.942 ERROR o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1216]- NODE 255: Timeout while sending message. Requeueing - 2 attempts left!
2015-01-14 07:52:24.944 DEBUG o.o.b.z.i.p.ZWaveController[:518]- Enqueueing message. Queue length = 4
2015-01-14 07:52:24.945 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1132]- Took message from queue for sending. Queue length = 3
2015-01-14 07:52:24.948 DEBUG o.o.b.z.i.p.SerialMessage[:232]- Assembled message buffer = 01 03 00 15 E9
2015-01-14 07:52:24.950 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1178]- NODE 255: Sending REQUEST Message = 01 03 00 15 E9
2015-01-14 07:52:28.987 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:29.546 WARN  o.o.b.z.i.p.ZWaveController$WatchDogTimerTask[:1447]- Threads not alive, respawning
2015-01-14 07:52:29.550 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1245]- Stopped Z-Wave thread: Send
2015-01-14 07:52:33.988 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:38.989 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:43.990 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:48.991 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:53.993 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:52:58.994 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!
2015-01-14 07:53:03.995 DEBUG o.o.b.z.i.ZWaveActiveBinding[:101]- Zwave Network isn't ready yet!```

but when I stop openhab and run domoticz (domoticz.com - I'm using it for some debugging and problem solving) it started working right away. When I stopped domoticz and runned openhab again issue exists again.

Any ideas?

Regards

**Comment by cdjackson** [comment]
What USB stick are you using?

**Comment by casperleenheer** [comment]
I have seen this behavior on my system (udoo/arm with Zwave S2 stick) also.
To solve it I have to shutdown (power off) the system and restart. After
this the system normally works ok.

Op Wed Jan 14 2015 at 13:03:59 schreef Chris Jackson <
notifications@github.com>:

**Comment by cdjackson** [comment]
The other thing to look at is the openhab log. There might be an exception in there - unfortunately zwave exceptions will often not be in the zwave log :(

**Comment by grzech1983** [comment]
Z-Stick S2. Regarding restarting thats another interesting thing because almost everytime I'm having this kind of issue I must plug out and plug in stick even when system was rebooted.

**Comment by casperleenheer** [comment]
Are you just rebooting or doing a power off? In my case a reboot doesn't
work. The stick needs to be powered off (or as in your case removed from
the port).

Op Wed Jan 14 2015 at 13:09:17 schreef grzech1983 <notifications@github.com

**Comment by cdjackson** [comment]
S2 certainly has problems - this is known, but probably won't be fixed by Aeon :( It's been discussed quite a bit on the Open ZWave forum -:

https://groups.google.com/forum/#!msg/openzwave/oM7VTuRVqv8/bztHcUOlH5kJ


Given that your device is not responding at all, it seems possible it's this, but if you can change back to Domotocz without resetting the stick then maybe not?
You could also try removing the softReset = true from the config - I don't think it will help with the S2, but some sticks (ZWave Plus) can lock up if sending the soft reset. I use the S2 at home and use softReset = true so it should be fine.

I would DEFINATELY look in the openhab.log file as I think you will find more information there - please send me the exception.

**Comment by grzech1983** [comment]
Is there a z-wave USB stick around which lets say works better?

Log entries (I'm using SSL with habmin and greent):

`09:35:53.404 WARN  o.e.j.servlet.ServletHandler[:553]- /services/habmin/zwave/nodes/
java.lang.RuntimeException: javax.ws.rs.WebApplicationException: javax.xml.bind.MarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException]
        at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:206)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:237)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:162)
        at org.atmosphere.container.Jetty7CometSupport.service(Jetty7CometSupport.java:94)
        at org.atmosphere.container.JettyAsyncSupportWithWebSocket.service(JettyAsyncSupportWithWebSocket.java:67)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1699)
Caused by: javax.ws.rs.WebApplicationException: javax.xml.bind.MarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException]
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:159)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
Caused by: javax.xml.bind.MarshalException: null
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:315)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
        at com.sun.jersey.json.impl.BaseJSONMarshaller.marshallToJSON(BaseJSONMarshaller.java:106)
        at com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider.writeTo(JSONRootElementProvider.java:143)
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:157)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
Caused by: javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException
        at com.sun.jersey.json.impl.writer.JsonXmlStreamWriter.flush(JsonXmlStreamWriter.java:197)
        at com.sun.xml.internal.bind.v2.runtime.output.XMLStreamWriterOutput.endDocument(XMLStreamWriterOutput.java:96)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.endDocument(XMLSerializer.java:841)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.postwrite(MarshallerImpl.java:362)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:309)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
Caused by: org.eclipse.jetty.io.EofException: null
        at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:952)
        at org.eclipse.jetty.http.AbstractGenerator.flush(AbstractGenerator.java:438)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:94)
        at org.eclipse.jetty.server.AbstractHttpConnection$Output.flush(AbstractHttpConnection.java:1022)
        at com.sun.jersey.spi.container.servlet.WebComponent$Writer.flush(WebComponent.java:315)
        at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.flush(ContainerResponse.java:145)
Caused by: javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1630)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1598)
        at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1528)
        at org.eclipse.jetty.io.nio.SslConnection.process(SslConnection.java:404)
        at org.eclipse.jetty.io.nio.SslConnection.access$900(SslConnection.java:43)


09:35:53.461 WARN  o.e.j.servlet.ServletHandler[:553]- /services/habmin/zwave/products/
java.lang.RuntimeException: javax.ws.rs.WebApplicationException: javax.xml.bind.MarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException]
        at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:206)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:237)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:162)
        at org.atmosphere.container.Jetty7CometSupport.service(Jetty7CometSupport.java:94)
        at org.atmosphere.container.JettyAsyncSupportWithWebSocket.service(JettyAsyncSupportWithWebSocket.java:67)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1699)
Caused by: javax.ws.rs.WebApplicationException: javax.xml.bind.MarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException]
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:159)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
Caused by: javax.xml.bind.MarshalException: null
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:315)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
        at com.sun.jersey.json.impl.BaseJSONMarshaller.marshallToJSON(BaseJSONMarshaller.java:106)
        at com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider.writeTo(JSONRootElementProvider.java:143)
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:157)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
Caused by: javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException
        at com.sun.jersey.json.impl.writer.JsonXmlStreamWriter.flush(JsonXmlStreamWriter.java:197)
        at com.sun.xml.internal.bind.v2.runtime.output.XMLStreamWriterOutput.endDocument(XMLStreamWriterOutput.java:96)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.endDocument(XMLSerializer.java:841)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.postwrite(MarshallerImpl.java:362)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:309)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
Caused by: org.eclipse.jetty.io.EofException: null
        at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:952)
        at org.eclipse.jetty.http.AbstractGenerator.flush(AbstractGenerator.java:438)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:94)
        at org.eclipse.jetty.server.AbstractHttpConnection$Output.flush(AbstractHttpConnection.java:1022)
        at com.sun.jersey.spi.container.servlet.WebComponent$Writer.flush(WebComponent.java:315)
        at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.flush(ContainerResponse.java:145)
Caused by: javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1630)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1598)
        at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1528)
        at org.eclipse.jetty.io.nio.SslConnection.process(SslConnection.java:404)
        at org.eclipse.jetty.io.nio.SslConnection.access$900(SslConnection.java:43)


09:35:53.509 ERROR c.s.j.s.i.a.WebApplicationImpl[:1483]- The response of the WebApplicationException cannot be utilized as the response is already committed. Re-throwing to the HTTP container
javax.ws.rs.WebApplicationException: javax.xml.bind.MarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException]
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:159)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
Caused by: javax.xml.bind.MarshalException: null
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:315)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
        at com.sun.jersey.json.impl.BaseJSONMarshaller.marshallToJSON(BaseJSONMarshaller.java:106)
        at com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider.writeTo(JSONRootElementProvider.java:143)
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:157)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
Caused by: javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException
        at com.sun.jersey.json.impl.writer.JsonXmlStreamWriter.flush(JsonXmlStreamWriter.java:197)
        at com.sun.xml.internal.bind.v2.runtime.output.XMLStreamWriterOutput.endDocument(XMLStreamWriterOutput.java:96)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.endDocument(XMLSerializer.java:841)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.postwrite(MarshallerImpl.java:362)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:309)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
Caused by: org.eclipse.jetty.io.EofException: null
        at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:952)
        at org.eclipse.jetty.http.AbstractGenerator.flush(AbstractGenerator.java:438)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:94)
        at org.eclipse.jetty.server.AbstractHttpConnection$Output.flush(AbstractHttpConnection.java:1022)
        at com.sun.jersey.spi.container.servlet.WebComponent$Writer.flush(WebComponent.java:315)
        at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.flush(ContainerResponse.java:145)
Caused by: javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1630)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1598)
        at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1528)
        at org.eclipse.jetty.io.nio.SslConnection.process(SslConnection.java:404)
        at org.eclipse.jetty.io.nio.SslConnection.access$900(SslConnection.java:43)

09:35:53.654 ERROR o.a.h.ReflectorServletProcessor[:205]- onRequest()
javax.ws.rs.WebApplicationException: javax.xml.bind.MarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException]
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:159)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
Caused by: javax.xml.bind.MarshalException: null
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:315)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
        at com.sun.jersey.json.impl.BaseJSONMarshaller.marshallToJSON(BaseJSONMarshaller.java:106)
        at com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider.writeTo(JSONRootElementProvider.java:143)
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:157)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
Caused by: javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException
        at com.sun.jersey.json.impl.writer.JsonXmlStreamWriter.flush(JsonXmlStreamWriter.java:197)
        at com.sun.xml.internal.bind.v2.runtime.output.XMLStreamWriterOutput.endDocument(XMLStreamWriterOutput.java:96)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.endDocument(XMLSerializer.java:841)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.postwrite(MarshallerImpl.java:362)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:309)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
Caused by: org.eclipse.jetty.io.EofException: null
        at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:952)
        at org.eclipse.jetty.http.AbstractGenerator.flush(AbstractGenerator.java:438)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:94)
        at org.eclipse.jetty.server.AbstractHttpConnection$Output.flush(AbstractHttpConnection.java:1022)
        at com.sun.jersey.spi.container.servlet.WebComponent$Writer.flush(WebComponent.java:315)
        at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.flush(ContainerResponse.java:145)
Caused by: javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1630)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1598)
        at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1528)
        at org.eclipse.jetty.io.nio.SslConnection.process(SslConnection.java:404)
        at org.eclipse.jetty.io.nio.SslConnection.access$900(SslConnection.java:43)`

**Comment by cdjackson** [comment]
Ok - I need to have a look at this tonight. It seems there is a bug here somewhere...

On sticks - I also have a Sigma UZB1 (zwave-plus) which I believe works ok, but I use it mostly on my development system. I think others are using this though, and there are more coming available (zwave.me which are also zwave-plus). I can't really comment though - my S2 works ok most of the time, but it does lock up every couple of months and as Capser says, you then need to remove it from the computer to reset it which is a real pain.

**Comment by cdjackson** [comment]
I don't know why this is happening for you, and not others (at least, not everyone!), but it should be fixed if you grab the latest version. For some reason it looks like it was trying to queue a null frame so I've added  a check to stop this.

**Comment by grzech1983** [comment]
Thanks. I'll update and let you know. For now I can only tell that after startup very quicky Aeon Multisensors have reported their temp and humidity (and I had some issues with them too).

**Comment by grzech1983** [comment]
After 20h of running I can tell that updating to latest verion of zwave binding and disabling softreset solved for now all of my problems.

**Comment by cdjackson** [comment]
Thanks for the feedback :)
